version: '3.8'

services:
  backend:
    image: kimseokryul/backend-app
    container_name: backend-app
    ports:
      - "8081:8080"
    volumes:
      - /opt/data/hls:/opt/data/hls
      - /opt/data/upload:/opt/data/upload
      - /opt/data/videos:/opt/data/videos
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    depends_on:
      - redis
      - rtmp-server

  frontend:
    image: kimseokryul/frontend-app
    container_name: frontend-app
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rtmp-server:
    build:
      context: ./rtmp-server
    container_name: rtmp-server
    ports:
      - "1935:1935"   # RTMP 수신 포트 (OBS용)
      - "80:80"     # HLS 재생 포트 (프론트에서 m3u8 접근)
    volumes:
      - /opt/data/hls:/opt/data/hls  # hls 저장 폴더 공유
    restart: always