version: '3.8'

services:
  backend:
    build:
      context: ./live-commerce-manager-backend
    container_name: backend-app
    ports:
      - "8081:8080"
    volumes:
      - /opt/data/upload:/opt/data/upload
      - /opt/data/videos:/opt/data/videos
    restart: always

  frontend:
    build:
      context: ./live-commerce-manager-frontend
    container_name: frontend-app
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - backend
