version: '3.8'

services:
  backend:
    image: kimseokryul/backend-app
    container_name: backend-app
    ports:
      - "8081:8080"
    volumes:
      - /opt/data/hls:/opt/data/hls
      - /opt/data/upload:/opt/data/upload
      - /opt/data/videos:/opt/data/videos
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    depends_on:
      - redis
      - rtmp-server

  frontend:
    image: kimseokryul/frontend-app
    container_name: frontend-app
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rtmp-server:
    image: alfg/nginx-rtmp
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "8090:80"
    volumes:
      - /opt/data/hls:/opt/data/hls
    restart: always
