name: CI Build Test

on:
  push:
    branches: [ develop ]
    pull_request:
      branches: [ main ]

jobs:
  build-backend:
    name: Build Spring Boot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Gradle
        working-directory: live-commerce-manager-backend
        run: ./gradlew build
  
  build-frontend:
    name: Build Vue App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: live-commerce-manager-frontend
        run: npm Install
      
      - name: Build frontend
        working-directory: live-commerce-manager-frontend
        run: npm run build